version: '3'
services:
  app:
    build: .
    volumes:
      - ~/git/github/favorite_videos:/var/www/app/
      - gem_data:/usr/local/bundle
    ports:
      - "80:80"
    links:
      - db
    environment:
      RAILS_ENV: development
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

volumes:
  gem_data:
  mysql_data:
