- name : install packages
  yum:
    name:
      - git
      - tree
      - wget
      - curl
      - gcc-c++
      - glibc-headers
      - openssl-devel
      - readline
      - libyaml-devel
      - readline-devel
      - zlib
      - zlib-devel
      - libffi-devel
      - libxml2
      - libxslt
      - libxml2-devel
      - libxslt-devel
      - sqlite-devel
      - ImageMagick
      - ImageMagick-devel
