- name: include tasks/ping.yml
  include_tasks: tasks/ping.yml

- name: include tasks/base-packages.yml
  include_tasks: tasks/base-packages.yml

- name: include tasks/user.yml
  include_tasks: tasks/user.yml
