- name: create user user
  user:
    name: "{{ item }}"
    state: present
    group: wheel
    shell: /bin/bash
  loop:
    - ansibleman

- name: set public key to login user
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMhZb58k/OzN89Hvw6bMtvwtO5ATRcFwQmqVKGNz2FVACE2hkJgNZfNzeW+FiWGojJoP+5XeEBxnh0EMZg/lFO5wByI+++bFrXX11LOyOIrx281jxzRz20h/L9jhrGNqrXHohVnj0UZzUjiVdCeETquOpQF2MAnzeOrrWDi2poz9x5avSOb4jV9aHbtgz7PtAlZJr7bwGTMzWdCfVkvCE3EsavxhWExudHuqD7Y7SY404SUrDZNWF8o1yGtXTF0Fjr+R39jZaHxVargf7ZZbHc79uhE1RqUREf2HEIvNTnCP0ePmkO1RbL6/bGF4HzowC6+3EHATKfB8fqvehb/3Ul shogo@shogonoMacBook-Air.local"
  loop:
    - ansibleman

- name: add user to sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ item }}"
    line: "{{ item }} ALL=(ALL) NOPASSWD: ALL"
  loop:
    - ansibleman

- cron:
    name: set cron for updating ssl
    minute: "0"
    hour: "4"
    day: "1"
    job: "/usr/bin/certbot renew && systemctl restart nginx"
    state: present
