default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: favorite_videos_development

test:
  <<: *default
  # port: 3306
  # host: '127.0.0.1'
  database: favorite_videos_test

production:
  <<: *default
  database: favorite_videos_production
