- name: "install-gcc"
  action: yum pkg=gcc state=installed

- name: Install nginx
  yum: name=nginx state=latest

- name: Set nginx service to start on boot
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Copy nginx.conf
  template: src=templates/nginx.conf dest=/etc/nginx/nginx.conf backup=true mode=0644
  notify: restart nginx

- name: Copy favorite_videos.com.conf
  template: src=templates/favorite_videos.com.conf dest=/etc/nginx/conf.d/ backup=true mode=0644
  notify: restart nginx
