- hosts: servers
  vars:
   repo_name: favorite_videos
  vars_prompt:
    -  name: "user_name"
       prompt: "Please Enter Your ID of Github"
       private: no
    -  name: "password"
       prompt: "Please Enter Your Password of Github"
       private: no
  roles:
    - common
    - nginx
    - ruby
